### ISSUE TITLE
Running on Linux: Unicode errors

### ISSUE THREAD

**Issue by 7eggert** [foreachthing/Slic3rConfigPrettyPrint#2]
Traceback (most recent call last):
  File "./Slic3rConfigPrettyPrint.py", line 69, in <module>
    out = open(dir_path/'slic3rconfigtable.tex','w')
TypeError: coercing to Unicode: need string or buffer, PosixPath found

This seems to work, but I don't know enough python to be sure:
out = open(str(dir_path)+os.sep+'slic3rconfigtable.tex','w')

Also:
dir_path = Path(filename).parent
dir_path_ = str(dir_path)+os.sep
...
out = open(dir_path_+'slic3rconfigtable.tex','w')           

**Next error:** Now I'm getting Somme silly snake-error has occured: <type 'exceptions.TypeError'>

(SoMMe typo occuRRed here)

At this point, I give up.

[Slic3rConfigPrettyPrint.py-2.patch.gz](https://github.com/foreachthing/Slic3rConfigPrettyPrint/files/2376752/Slic3rConfigPrettyPrint.py-2.patch.gz)

**Comment by foreachthing** [comment]
Ok! Sooo, THANKS for testing it on Linux....
I need to look into that one! I thought with the pathlib I was safe on any OS.

**Comment by foreachthing** [comment]
Please give d076c275542eaac3c05c64655130dc208d3654fa a try!
Tested with Ubunut 16.04 LTS and TeX Live 2015/Debian

**Comment by 7eggert** [comment]
Now it did exit with "[Errno 2] No such file or directory"  when pdflatex is not installed. (should be own bug reports, if you prefer)

**Documentation:**
On Debian-Jessie it also needs xstring menukeys siunitx ltablex etoolbox adjustbox collectbox relsize catoptions marginnote titlesec trimspaces environ l3kernel 
if the extra texlife package is not installed (550 MB)

Also texlive-fonts-recommended and python-pathlib need to be installed

**Last problem:**
 \ in gcode files needs to be escaped, too:

`; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"`

(Currently "\n" remains and "\\n" is expanded to "\ \n".)

**Comment by foreachthing** [comment]
start and end filament code should be fixed in latest commit.
Closing here.

**Comment by 7eggert** [comment]
Semi-confirmed; I experimentally wrote \\n into the gcode file to have \\ in the tex file. \n was handled correctly, but the extra \ did not display as expected. I don' t expect this to be a problem.

**Comment by foreachthing** [comment]
Uhm ... So, you want the `\n` in the report?
I parsed it the way it would actually break the line. Slic3r automatically writes a `\n` when you save your settings.

**Comment by 7eggert** [comment]
No, but if there was a \\ in the gcode text box and therefore a \\\\ in the gcode comment, it should print as \\.

But I just now tested that, too, a \\ in the custom gcode box gcode will be lost while generating the gcode, so there should not be a \\ in there. That's a bug that might eventually get fixed.
